services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    hostname: keycloak.host
    restart: unless-stopped
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=${KC_BOOTSTRAP_ADMIN_USERNAME}
      - KC_BOOTSTRAP_ADMIN_PASSWORD=${KC_BOOTSTRAP_ADMIN_PASSWORD}
      - KC_DB_URL=${KC_DB_URL}
      - KC_DB=${KC_DB}
      - KC_DB_USERNAME=${POSTGRES_USER}
      - KC_DB_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - 9080:8080
    networks:
      infrastructure-network:
        aliases:
          - keycloak.host
    command:
      - start
      - --http-enabled=true
      - --proxy-headers=xforwarded
      - --http-relative-path=/auth
      - --hostname-strict=false
networks:
  infrastructure-network:
    external: true

