services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    networks:
      - infrastructure-network
    ports:
      - 80:80
      - 443:443
    environment:
      - NGINX_MAIN_DOMAIN=${NGINX_MAIN_DOMAIN}
    volumes:
      - ./nginx.conf.template:/etc/nginx/templates/nginx.conf.template
      - ./certs/certificate.crt:/etc/nginx/ssl/certificate.crt
      - ./certs/private_key.key:/etc/nginx/ssl/private_key.key
    command: >
      sh -c "envsubst \"`env | awk -F = '{printf \" \\\\$%s\", $1}'`\" < /etc/nginx/templates/nginx.conf.template > /etc/nginx/nginx.conf &&
         nginx -g 'daemon off;'"

networks:
  infrastructure-network:
    external: true

